### ISSUE TITLE
[ADD] Adicionar teste para a função "data_eh_feriado_bancario"

### ISSUE THREAD

**Issue by hendrixcosta** [kmee/l10n-brazil#308]
NO módulo l10n_br_resource

Adicionar teste para a função "data_eh_feriado_bancario"

A função esta em l10n_br_resource/models/inherited_resource_calendar.py

**Comment by Hendrixcosta** [comment]
![image](https://user-images.githubusercontent.com/7250580/32049399-af36f366-ba2b-11e7-93fd-92aeb66dce38.png)

**Comment by BiancaBartolomei** [comment]
#310
